<a href="https://colab.research.google.com/github/LucyMariel/Lucy/blob/master/DIVICMatrixProd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Matrix product**

Consider the following matrices A and B. When expressed in NumPy, it becomes as follows.
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

**[Problem 1] Matrix product is calculated manually**


Solve the matrix product of A and B by hand.
Please also explain the calculation process using markdown text.

First Row of
𝐴
A and Columns of
𝐵
B:
𝐶
11
=
(
−
1
⋅
0
)
+
(
2
⋅
0
)
+
(
3
⋅
2
)
=
0
+
0
+
6
=
6
C
11
​
 =(−1⋅0)+(2⋅0)+(3⋅2)=0+0+6=6

𝐶
12
=
(
−
1
⋅
2
)
+
(
2
⋅
2
)
+
(
3
⋅
9
)
=
−
2
+
4
+
27
=
29
C
12
​
 =(−1⋅2)+(2⋅2)+(3⋅9)=−2+4+27=29

𝐶
13
=
(
−
1
⋅
1
)
+
(
2
⋅
−
8
)
+
(
3
⋅
−
1
)
=
−
1
−
16
−
3
=
−
20
C
13
​
 =(−1⋅1)+(2⋅−8)+(3⋅−1)=−1−16−3=−20


Second Row of
𝐴
A and Columns of
𝐵
B:
𝐶
21
=
(
4
⋅
0
)
+
(
−
5
⋅
0
)
+
(
6
⋅
2
)
=
0
+
0
+
12
=
12
C
21
​
 =(4⋅0)+(−5⋅0)+(6⋅2)=0+0+12=12

𝐶
22
=
(
4
⋅
2
)
+
(
−
5
⋅
2
)
+
(
6
⋅
9
)
=
8
−
10
+
54
=
52
C
22
​
 =(4⋅2)+(−5⋅2)+(6⋅9)=8−10+54=52

𝐶
23
=
(
4
⋅
1
)
+
(
−
5
⋅
−
8
)
+
(
6
⋅
−
1
)
=
4
+
40
−
6
=
38
C
23
​
 =(4⋅1)+(−5⋅−8)+(6⋅−1)=4+40−6=38


Third Row of
𝐴
A and Columns of
𝐵
B:
𝐶
31
=
(
7
⋅
0
)
+
(
8
⋅
0
)
+
(
−
9
⋅
2
)
=
0
+
0
−
18
=
−
18
C
31
​
 =(7⋅0)+(8⋅0)+(−9⋅2)=0+0−18=−18

𝐶
32
=
(
7
⋅
2
)
+
(
8
⋅
2
)
+
(
−
9
⋅
9
)
=
14
+
16
−
81
=
−
51
C
32
​
 =(7⋅2)+(8⋅2)+(−9⋅9)=14+16−81=−51

𝐶
33
=
(
7
⋅
1
)
+
(
8
⋅
−
8
)
+
(
−
9
⋅
−
1
)
=
7
−
64
+
9
=
−
48
C
33
​
 =(7⋅1)+(8⋅−8)+(−9⋅−1)=7−64+9=−48


Multiply the first row of A by the corresponding element of the first column of
B, and then sum the products. Then the same process for other rows and columns.


**[Problem 2] Calculation by NumPy function**

This matrix product of NumPy can be easily calculated using np.matmul() or np.dot() , or the @ operator.

Use these to calculate the matrix product.

numpy.matmul — NumPy v1.16 Manual

numpy.dot — NumPy v1.16 Manual

《Three types of difference》

 np.matmul()  and  np.dot()  behave differently in 3D or higher arrays. The  @  operator works the same as  np.matmul() .

In the matrix multiplication of a two-dimensional array like this time np.matmul() or @ Operators are officially recommended. The following is a quote from the explanation of np.dot() .

Matrix product using np.matmul()

In [2]:
import numpy as np

# Define matrices A and B
A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Calculate the matrix product using np.matmul()
C = np.matmul(A, B)

# Print the resulting matrix
print("Matrix product of A and B:")
print(C)

Matrix product of A and B:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


Matrix product using np.dot()

In [3]:
import numpy as np

# Define matrices A and B
A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Calculate the matrix product using np.dot()
C = np.dot(A, B)

# Print the resulting matrix
print("Matrix product of A and B using np.dot():")
print(C)

Matrix product of A and B using np.dot():
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


Matrix product using @

In [4]:
import numpy as np

# Define matrices A and B
A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Calculate the matrix product using the @ operator
C = A @ B

# Print the resulting matrix
print("Matrix product of A and B using the @ operator:")
print(C)

Matrix product of A and B using the @ operator:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


**Scratch implementation of matrix product [Problem 3] Implementation of calculation of a certain element**

When doing the calculations by hand, you may have first paid attention to row 0 of matrix A and column 0 of matrix B, and then performed the following calculations.

Multiply the (0,0) element $a_{0, 0}$ of matrix A with the (0,0) element $b_{0, 0}$ of matrix B
Multiply the (0,1) element $a_{0, 1}$ of matrix A with the (1,0) element $b_{1, 0}$ of matrix B
Multiply the (0,2) element $a_{0, 2}$ of matrix A with the (2,0) element $b_{2, 0}$ of matrix B
Add all those values together
Expressed as a formula

2
∑
K
=
0

a
0
,
K
b
K
,
0



Write code to do this calculation without using np.matmul() , np.dot() or @ operators.



In [5]:
import numpy as np

# Define matrices A and B
A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Initialize the result matrix with zeros
C = np.zeros((A.shape[0], B.shape[1]))

# Perform the manual matrix multiplication
for i in range(A.shape[0]):
    for j in range(B.shape[1]):
        for k in range(A.shape[1]):
            C[i, j] += A[i, k] * B[k, j]

# Print the resulting matrix
print("Matrix product of A and B calculated manually:")
print(C)

Matrix product of A and B calculated manually:
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


**[Problem 4] Creating a function that performs matrix multiplication**

Extend the code in Problem 3 to complete the matrix product scratch implementation. It should be a function that takes matrices A and B as arguments and returns the matrix product.

When calculating the matrix product, you will repeat the calculation in Problem 3 for different rows and columns.

Each element $c_{i, j}$ of the matrix C of the calculated result $3 \times 3$ is expressed as follows.

c
i
,
j
=
2
∑
K
=
0

a
i
,
K
b
K
,
j
By using the for statement and moving the index of ndarray, a total of 9 elements can be calculated. You can increase the index $i$ or $j$ by 1 to move to the next row or column.

In [6]:
import numpy as np

def matrix_product(A, B):
    # Get the dimensions of the input matrices
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape

    # Ensure the matrices can be multiplied (i.e., cols_A == rows_B)
    if cols_A != rows_B:
        raise ValueError("The number of columns in A must be equal to the number of rows in B")

    # Initialize the result matrix with zeros
    C = np.zeros((rows_A, cols_B))

    # Perform the manual matrix multiplication
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                C[i, j] += A[i, k] * B[k, j]

    return C

# Define matrices A and B
A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Calculate the matrix product using the custom function
C = matrix_product(A, B)

# Print the resulting matrix
print("Matrix product of A and B using custom function:")
print(C)

Matrix product of A and B using custom function:
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


**A combination of matrices with undefined matrix products**

Now consider the following example

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

**[Problem 5] Judge the input whose calculation is not defined**

Depending on the implementation method, the function created in Problem 4 may work even if this D and E array is input. In this case, incorrect calculations will be made. Also, even if an error occurs in the middle, a message that is hard to understand why the error occurred is displayed directly.

You can prevent this by using an if statement or similar, and add code to display the problem in the input form using print() .

In [9]:
import numpy as np

def matrix_product(A, B):
    # Get the dimensions of the input matrices
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape

    # Ensure the matrices can be multiplied (i.e., cols_A == rows_B)
    if cols_A != rows_B:
        raise ValueError("The number of columns in A must be equal to the number of rows in B")
        print()
    # Initialize the result matrix with zeros
    C = np.zeros((rows_A, cols_B))

    # Perform the manual matrix multiplication
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                C[i, j] += A[i, k] * B[k, j]

    return C

# Define matrices d_ndarray and e_ndarray
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

# Calculate the matrix product using the custom function
C = matrix_product(d_ndarray, e_ndarray)

# Print the resulting matrix
print("Matrix product of d_ndarray and e_ndarray using custom function:")
print(C)

ValueError: The number of columns in A must be equal to the number of rows in B

In [8]:
import numpy as np

def matrix_product(A, B):
    # Get the dimensions of the input matrices
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape

    # Print the dimensions of the matrices
    print(f"Dimensions of matrix A: {rows_A}x{cols_A}")
    print(f"Dimensions of matrix B: {rows_B}x{cols_B}")

    # Ensure the matrices can be multiplied (i.e., cols_A == rows_B)
    if cols_A != rows_B:
        print("Matrix A columns:", cols_A)
        print("Matrix B rows:", rows_B)
        raise ValueError("The number of columns in A must be equal to the number of rows in B")

    # Initialize the result matrix with zeros
    C = np.zeros((rows_A, cols_B))

    # Perform the manual matrix multiplication
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                C[i, j] += A[i, k] * B[k, j]

    return C

# Define matrices d_ndarray and e_ndarray
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])  # Incorrect dimensions

# Calculate the matrix product using the custom function
try:
    C = matrix_product(d_ndarray, e_ndarray)
    # Print the resulting matrix if multiplication is possible
    print("Matrix product of d_ndarray and e_ndarray using custom function:")
    print(C)
except ValueError as e:
    print(e)

# Define matrices with correct dimensions for demonstration
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray_correct = np.array([[-9, 8], [7, 6], [-5, 4]])

# Calculate the matrix product using the custom function with correct dimensions
try:
    C_correct = matrix_product(d_ndarray, e_ndarray_correct)
    # Print the resulting matrix if multiplication is possible
    print("Matrix product of d_ndarray and e_ndarray_correct using custom function:")
    print(C_correct)
except ValueError as e:
    print(e)

Dimensions of matrix A: 2x3
Dimensions of matrix B: 2x3
Matrix A columns: 3
Matrix B rows: 2
The number of columns in A must be equal to the number of rows in B
Dimensions of matrix A: 2x3
Dimensions of matrix B: 3x2
Matrix product of d_ndarray and e_ndarray_correct using custom function:
[[   8.   16.]
 [-101.   26.]]


**[Problem 6] Transposition**

Transposing one matrix allows you to calculate the matrix product.

Transpose it using the np.transpose() or .T attributes and calculate the matrix product.

In [10]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

In [11]:
# Transpose the matrices using .T attribute
a_transposed = a_ndarray.T
b_transposed = b_ndarray.T

print("Transpose of a_ndarray using .T:")
print(a_transposed)
print("Transpose of b_ndarray using .T:")
print(b_transposed)

# Calculate the matrix product of the transposed matrices
product_transposed = np.matmul(a_transposed, b_transposed)

print("Matrix product of transposed matrices using np.matmul():")
print(product_transposed)

# Transpose the matrices using np.transpose()
a_transposed_np = np.transpose(a_ndarray)
b_transposed_np = np.transpose(b_ndarray)

print("Transpose of a_ndarray using np.transpose():")
print(a_transposed_np)
print("Transpose of b_ndarray using np.transpose():")
print(b_transposed_np)

# Calculate the matrix product of the transposed matrices
product_transposed_np = np.matmul(a_transposed_np, b_transposed_np)

print("Matrix product of transposed matrices using np.matmul() with np.transpose():")
print(product_transposed_np)

Transpose of a_ndarray using .T:
[[-1  4  7]
 [ 2 -5  8]
 [ 3  6 -9]]
Transpose of b_ndarray using .T:
[[ 0  0  2]
 [ 2  2  9]
 [ 1 -8 -1]]
Matrix product of transposed matrices using np.matmul():
[[ 15 -48  27]
 [ -2 -74 -49]
 [  3  84  69]]
Transpose of a_ndarray using np.transpose():
[[-1  4  7]
 [ 2 -5  8]
 [ 3  6 -9]]
Transpose of b_ndarray using np.transpose():
[[ 0  0  2]
 [ 2  2  9]
 [ 1 -8 -1]]
Matrix product of transposed matrices using np.matmul() with np.transpose():
[[ 15 -48  27]
 [ -2 -74 -49]
 [  3  84  69]]
